project_name: Artificer
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - skip: false

changelog:
  sort: "asc"
  filters:
    exclude:
      - "^docs:" 